In [32]:
import numpy as np
a=np.array([1,2,3,])
print(type(a))

<class 'numpy.ndarray'>


In [9]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(a+b)
print(a*b)



[3 5 7 9]
[ 2  6 12 20]


In [23]:
b=10
c=b
b=13
print(b,c)


13 10


1735814592

In [26]:
a=[1,2,5]
b=a
b[0]=10
print(a,b)
print(id(a))
print(id(b))

[10, 2, 5] [10, 2, 5]
2298326238856
2298326238856


In [35]:
a=[1,2,5]
b=a.copy()
b[0]=10
print(a,b)
print(id(a),id(b))
#print(id(b))

[1, 2, 5] [10, 2, 5]
2298320814856 2298321911048


In [34]:
a=np.array([1,2,3,])
print(a.dtype)

int32


In [36]:
a=np.array([1,2,3,4],dtype=np.int8)
a

array([1, 2, 3, 4], dtype=int8)

In [39]:
a=np.array([1,2,3,4],dtype=np.float16)
a

array([1., 2., 3., 4.], dtype=float16)

In [2]:
while(1):
    b=[]
    c=[]
    n=int(input("Enter dimentions of array"))
    for i in range(1,n+1):
        a=int(input())
        #b=[]
        b.append(a)
        print(b)
    for j in range(1,n+1):
        d=int(input())
        c.append(d)
        print(c)
    import numpy as np
    choice=int(input("Enter your choice"))
    np.array(b)
    np.array(c)
        if choice==1:
            print(b+c)
        else:
            break



IndentationError: unexpected indent (<ipython-input-2-49504b382545>, line 18)

In [1]:
import time
import numpy as np
a=time.time()
d=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=0
for i in range(4):
    c+=d[i]*b[i]
print(c)
print(time.time()-a)


30
0.0009717941284179688


In [7]:
b=np.array([1,2,3,4])
np.save('6',b)
b=np.load('abc.npy')
print(b)


[1 2 3 4]


In [12]:
a=np.zeros((2,2))
print(a)
a=np.ones((2,2))
print(a)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [13]:
#c=np.arrange(start,end,stop)

In [14]:
a=np.full((2,2),7)
print(a)

[[7 7]
 [7 7]]
